### PR TITLE
Updating Readme Image

### PR DESCRIPTION
**Pull request by SarahhhhFoster**
Making the initial image more usable as a reference

### CODE REVIEW

**Comment by Jana-Marie** [comment]
Wow, thanks! Looks great!

**Comment by SarahhhhFoster** [comment]
I'm hype you liked it! It's a great project; let me know if it makes its way onto Tindie or anything like!

**Comment by Jana-Marie** [comment]
Hey, people on twitter wonder how create something like this? Maybe you can join the discussion if you have twitter :) https://twitter.com/bitshiftmask/status/1319188146408574976

**Comment by SarahhhhFoster** [comment]
For any inquiring minds that make their way here, [here](https://twitter.com/bratzfan101/status/1319325488708423682) is my response ^_^

**Pull request merged**
